### ISSUE TITLE
Docker volume not persisting

### ISSUE THREAD

**Issue by cmdln156** [lrswss/docker-frost-http#1]
Thanks for providing a docker image for FROST-Server for the Raspberry Pi!

After getting it working, I'm finding that the stored data in the docker volume doesn't seem to persist after running "docker compose down" and then "up" again. Whatever data I loaded into FROST-Server is gone. The original FraunhoferIOSB image doesn't do this -- it retains the data after restarting. 

I'm not sure if I'm missing something, but any help would be appreciated.

**Comment by lrswss** [comment]
First use `docker-compose up`, and then `stop` and `start` to stop and restart the containers.

**Comment by cmdln156** [comment]
Thanks for the reply. Yes, I realize that if I use 'docker stop' and
'start', then the data will be retained, but I was wondering why it doesn't
persist when you restart after 'docker down', like the Fraunhofer image.

**Comment by lrswss** [comment]
Fixed. Tracked it down to an invalid volume path for the postgresql data directory in the included postgresql-postgis image. Had to update db init script as well. The new version also uses an updated FROST-HTTP 1.14 image with recent jar dependencies. Please clone the updated repository and try again.

**Comment by cmdln156** [comment]
I just tried it out. It works perfectly now -- the data persists after
restarting from 'docker down'. Thanks very much for fixing it so quickly!

**Comment by lrswss** [comment]
Thank you for pointing out the issue in the first place. 👍
